name: Prettier
on: [push]
jobs:
  prettify_all:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - name: Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          prettier_plugins: "prettier-plugin-java prettier-plugin-properties"
